// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: engram.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/structpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// This is a placeholder file to allow the SDK to compile.
// Replace this with the actual generated protobuf code.

// Mocks for grpc client
type EngramServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	ExecuteStream(ctx context.Context, opts ...grpc.CallOption) (EngramService_ExecuteStreamClient, error)
}
type engramServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngramServiceClient(cc grpc.ClientConnInterface) EngramServiceClient {
	return &engramServiceClient{cc}
}
func (c *engramServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	return nil, nil
}
func (c *engramServiceClient) ExecuteStream(ctx context.Context, opts ...grpc.CallOption) (EngramService_ExecuteStreamClient, error) {
	return nil, nil
}

type EngramService_ExecuteStreamClient interface {
	Send(*StreamMessage) error
	Recv() (*StreamMessage, error)
	grpc.ClientStream
}
type engramServiceExecuteStreamClient struct {
	grpc.ClientStream
}

func (x *engramServiceExecuteStreamClient) Send(m *StreamMessage) error {
	return x.ClientStream.SendMsg(m)
}
func (x *engramServiceExecuteStreamClient) Recv() (*StreamMessage, error) {
	m := new(StreamMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Mocks for grpc server
func RegisterEngramServiceServer(s grpc.ServiceRegistrar, srv EngramServiceServer) {}

type EngramServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedEngramServiceServer()
}

type UnimplementedEngramServiceServer struct{}

func (UnimplementedEngramServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, nil
}
func (UnimplementedEngramServiceServer) mustEmbedUnimplementedEngramServiceServer() {}

type ExecuteRequest struct {
	Context *ExecutionContext
}

type ExecutionContext struct {
	StoryName       string
	StoryRunId      string
	StepName        string
	StepRunId       string
	ParentStepRunId string
	Config          *structpb.Struct
	Inputs          *structpb.Struct
	Mode            ProcessingMode
	Environment     map[string]string
}

type ExecuteResponse struct {
	Success    bool
	Data       *structpb.Struct
	Error      string
	Metadata   map[string]string
	Metrics    map[string]float64
	DurationMs int64
}

type StreamMessage struct {
	Type      StreamMessageType
	MessageId string
	SessionId string
	Payload   *structpb.Struct
	Metadata  map[string]string
	Timestamp *timestamppb.Timestamp
}

type HealthCheckRequest struct{}
type HealthCheckResponse struct {
	Status  HealthStatus
	Message string
	Details map[string]string
}

type MetricsRequest struct{}
type MetricsResponse struct {
	Metrics   map[string]float64
	Timestamp *timestamppb.Timestamp
}

type ProcessingMode int32

const (
	ProcessingMode_PROCESSING_MODE_BATCH    ProcessingMode = 0
	ProcessingMode_PROCESSING_MODE_REALTIME ProcessingMode = 1
	ProcessingMode_PROCESSING_MODE_STREAM   ProcessingMode = 2
)

type StreamMessageType int32

const (
	StreamMessageType_STREAM_MESSAGE_TYPE_CONTROL StreamMessageType = 0
	StreamMessageType_STREAM_MESSAGE_TYPE_DATA    StreamMessageType = 1
	StreamMessageType_STREAM_MESSAGE_TYPE_ACK     StreamMessageType = 2
	StreamMessageType_STREAM_MESSAGE_TYPE_ERROR   StreamMessageType = 3
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNKNOWN     HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING HealthStatus = 2
)
